# Generated by Django 4.1.4 on 2022-12-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeckList',
            new_name='Card',
        ),
    ]
