# Generated by Django 4.1.4 on 2022-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_deck_cards_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards_id',
            field=models.ManyToManyField(to='cards.card'),
        ),
    ]
