# Generated by Django 4.1.4 on 2022-12-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_decklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardList',
            new_name='EntryList',
        ),
        migrations.RemoveField(
            model_name='card',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards_id',
        ),
        migrations.AddField(
            model_name='decklist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
