# Generated by Django 4.1.4 on 2022-12-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_cardlist_entrylist_remove_card_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylist',
            name='card',
        ),
        migrations.AddField(
            model_name='entrylist',
            name='card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
            preserve_default=False,
        ),
    ]
