# Generated by Django 4.1.4 on 2022-12-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_entrylist_card_entrylist_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrylist',
            old_name='card_id',
            new_name='card',
        ),
    ]
